{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mango.sdk",
    "module": "translate-android",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "translate-android-0.1.3.aar",
          "url": "translate-android-0.1.3.aar",
          "size": 1160732,
          "sha512": "de071b968c3b9017c03113743aad2b3b6dc83c7f355f8efe1277885ee640b933f237d0eb34135ba7303736fa28a958cba41f781abff68a2207782af35c9be9b2",
          "sha256": "157cc7ee4a0168663f00cb97b8f429b71b3f80a55359b38b78415bac6edccf32",
          "sha1": "42db1f9fd54adaf946e54e3220590e707cde6c04",
          "md5": "9b132a243b1262d9ec0b767a6e088163"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-scalars",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "translate-android-0.1.3.aar",
          "url": "translate-android-0.1.3.aar",
          "size": 1160732,
          "sha512": "de071b968c3b9017c03113743aad2b3b6dc83c7f355f8efe1277885ee640b933f237d0eb34135ba7303736fa28a958cba41f781abff68a2207782af35c9be9b2",
          "sha256": "157cc7ee4a0168663f00cb97b8f429b71b3f80a55359b38b78415bac6edccf32",
          "sha1": "42db1f9fd54adaf946e54e3220590e707cde6c04",
          "md5": "9b132a243b1262d9ec0b767a6e088163"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "translate-android-0.1.3-sources.jar",
          "url": "translate-android-0.1.3-sources.jar",
          "size": 216777,
          "sha512": "0316d410f8dc928bf315cd28bb902b68b499bf2d0463bde6ce9b3cbc911969fca7050e29cb228193cb93db9a69108451d187c0fc83aae693ea484d3dcb9596f5",
          "sha256": "0abb4ad849c6b54c8084632dc972bfb0a6a9488e631304c3f034abceac6d0d7b",
          "sha1": "d9d6d8616597d3c242fd27b040a5bd524284e540",
          "md5": "d8761e9566fe0b6318894f3bab9befb4"
        }
      ]
    }
  ]
}
