{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mango.sdk",
    "module": "translate-android",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "translate-android-0.2.1.aar",
          "url": "translate-android-0.2.1.aar",
          "size": 1219691,
          "sha512": "7d79297ae5659103147d99ef17bb687cb79f72ac894c55bf3821e48a825c06a2cfdc80b125f6368d2287d0451aedda4c70b45206291e84fd5e80b2d7aed03635",
          "sha256": "8158ccef4d132622dc87457fc9460dbc6e7367222d34e17730f38bfe1706c795",
          "sha1": "c5aa6ae78d021933a5e7b7fa55b6964043cdf711",
          "md5": "b373aefdce36d95fc7b642deea673877"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-scalars",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava2",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "translate-android-0.2.1.aar",
          "url": "translate-android-0.2.1.aar",
          "size": 1219691,
          "sha512": "7d79297ae5659103147d99ef17bb687cb79f72ac894c55bf3821e48a825c06a2cfdc80b125f6368d2287d0451aedda4c70b45206291e84fd5e80b2d7aed03635",
          "sha256": "8158ccef4d132622dc87457fc9460dbc6e7367222d34e17730f38bfe1706c795",
          "sha1": "c5aa6ae78d021933a5e7b7fa55b6964043cdf711",
          "md5": "b373aefdce36d95fc7b642deea673877"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "translate-android-0.2.1-sources.jar",
          "url": "translate-android-0.2.1-sources.jar",
          "size": 233122,
          "sha512": "d63df6c07998fe4309013877da397d8fba02ce67b9efe3928a74d76d8404090b5f334934e8b4e365cab671bd77c46b7513ad226e6d268093e10117a6591a20fb",
          "sha256": "ef0f7bcf365d0e0b217d08a25b0f10c5c30533bf22a033113e44caa355981849",
          "sha1": "eca9612cc3a504828f8c8057fe7ecfaaa4dc2c30",
          "md5": "d93cfde84d41613d3a759a335426cd71"
        }
      ]
    }
  ]
}
